from __future__ import annotations

import argparse
import csv
import math
import re
from pathlib import Path

AXIS_MIN = 1e-1
DEFAULT_PARNV_TIMEOUT_SECONDS = 1400.0
DEFAULT_NARV_TIMEOUT_SECONDS = 1400.0
PARNV_TIME_FIELDS = ("elapsed_seconds",)
NARV_TIME_FIELDS = ("elapsed_seconds",)
TIMEOUT_TEXT = "TIMEOUT"


def parse_args() -> argparse.Namespace:
    script_dir = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(
        description=(
            "Plot ACAS Xu verification time of PARnv against NARv, "
            "paired by network id and property id."
        )
    )
    parser.add_argument(
        "--parnv-csv",
        type=Path,
        default=script_dir / "ACASXu" / "parnv_narv_006.csv",
        help="CSV generated by the PARnv verification run.",
    )
    parser.add_argument(
        "--narv-csv",
        type=Path,
        default=script_dir / "ACASXu" / "narv_006.csv",
        help="CSV generated by the NARv verification run.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=script_dir / "ACASXu" / "acasxu_parnv_vs_narv_6_scatter.png",
        help="Output image path.",
    )
    parser.add_argument(
        "--parnv-timeout-seconds",
        type=float,
        default=DEFAULT_PARNV_TIMEOUT_SECONDS,
        help="X-axis value used for PARnv timeout markers.",
    )
    parser.add_argument(
        "--narv-timeout-seconds",
        type=float,
        default=DEFAULT_NARV_TIMEOUT_SECONDS,
        help="Y-axis value used for NARv timeout markers.",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=220,
        help="Output image DPI.",
    )
    return parser.parse_args()


def read_csv_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", newline="", encoding="utf-8-sig") as csv_file:
        return list(csv.DictReader(csv_file))


def parse_positive_float(raw_value: str | None) -> float | None:
    text = (raw_value or "").strip()
    if not text:
        return None
    try:
        value = float(text)
    except ValueError:
        return None
    if not math.isfinite(value) or value <= 0.0:
        return None
    return value


def parse_positive_float_by_fields(row: dict[str, str], fields: tuple[str, ...]) -> float | None:
    for field in fields:
        value = parse_positive_float(row.get(field))
        if value is not None:
            return value
    return None


def normalize_network_id(row: dict[str, str]) -> str | None:
    for field in ("network_id", "net_id", "net_number"):
        value = (row.get(field) or "").strip()
        if re.fullmatch(r"\d+_\d+", value):
            return value

    for field in ("network", "network_name", "net_name"):
        value = (row.get(field) or "").strip()
        for pattern in (
            r"ACASXU_run2a_(\d+)_(\d+)_batch_2000\.nnet",
            r"ACASXu_(\d+)_(\d+)\.nnet",
        ):
            match = re.search(pattern, value, re.IGNORECASE)
            if match:
                return f"{match.group(1)}_{match.group(2)}"
    return None


def normalize_property_id(row: dict[str, str]) -> str | None:
    property_id = (row.get("property_id") or "").strip()
    if not property_id:
        return None

    adversarial_match = re.fullmatch(r"adversarial_(\d+)", property_id, re.IGNORECASE)
    if adversarial_match:
        return adversarial_match.group(1)

    digit_match = re.fullmatch(r"\d+", property_id)
    if digit_match:
        return property_id

    return property_id


def is_timeout_row(row: dict[str, str]) -> bool:
    status_fields = (
        "status",
        "query_result",
        "verification_result",
        "error_type",
        "error_message",
        "error",
    )
    return any(TIMEOUT_TEXT in (row.get(field) or "").upper() for field in status_fields)


def cap_time_at_timeout(
    time_value: float | None,
    timeout_seconds: float,
    timeout_from_status: bool,
) -> tuple[float | None, bool]:
    if time_value is None:
        if timeout_from_status:
            return timeout_seconds, True
        return None, False
    if timeout_from_status or time_value >= timeout_seconds:
        return timeout_seconds, True
    return time_value, False


def row_key(row: dict[str, str]) -> tuple[str, str] | None:
    net_id = normalize_network_id(row)
    property_id = normalize_property_id(row)
    if net_id is None or property_id is None:
        return None
    return net_id, property_id


def rows_by_key(rows: list[dict[str, str]]) -> dict[tuple[str, str], dict[str, str]]:
    keyed_rows: dict[tuple[str, str], dict[str, str]] = {}
    for row in rows:
        key = row_key(row)
        if key is not None:
            keyed_rows[key] = row
    return keyed_rows


def build_paired_points(
    parnv_rows: list[dict[str, str]],
    narv_rows: list[dict[str, str]],
    parnv_timeout_seconds: float,
    narv_timeout_seconds: float,
) -> tuple[list[tuple[float, float]], list[tuple[float, float]], int, int, int]:
    parnv_by_key = rows_by_key(parnv_rows)
    narv_by_key = rows_by_key(narv_rows)
    paired_keys = sorted(set(parnv_by_key).intersection(narv_by_key))

    finished_points: list[tuple[float, float]] = []
    timeout_points: list[tuple[float, float]] = []
    skipped_pairs = 0

    for key in paired_keys:
        parnv_row = parnv_by_key[key]
        narv_row = narv_by_key[key]

        parnv_time = parse_positive_float_by_fields(parnv_row, PARNV_TIME_FIELDS)
        narv_time = parse_positive_float_by_fields(narv_row, NARV_TIME_FIELDS)
        parnv_timeout = is_timeout_row(parnv_row)
        narv_timeout = is_timeout_row(narv_row)

        parnv_time, parnv_timeout = cap_time_at_timeout(
            parnv_time,
            parnv_timeout_seconds,
            parnv_timeout,
        )
        narv_time, narv_timeout = cap_time_at_timeout(
            narv_time,
            narv_timeout_seconds,
            narv_timeout,
        )

        if parnv_time is None or narv_time is None:
            skipped_pairs += 1
            continue

        point = (max(parnv_time, AXIS_MIN), max(narv_time, AXIS_MIN))
        if parnv_timeout or narv_timeout:
            timeout_points.append(point)
        else:
            finished_points.append(point)

    return (
        finished_points,
        timeout_points,
        skipped_pairs,
        len(parnv_by_key) - len(paired_keys),
        len(narv_by_key) - len(paired_keys),
    )


def plot_points(
    finished_points: list[tuple[float, float]],
    timeout_points: list[tuple[float, float]],
    output_path: Path,
    parnv_timeout_seconds: float,
    narv_timeout_seconds: float,
    dpi: int,
) -> None:
    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(figsize=(5.8, 3.6))

    if finished_points:
        x_values, y_values = zip(*finished_points, strict=True)
        ax.scatter(
            x_values,
            y_values,
            color="#2f55ff",
            alpha=0.18,
            s=34,
            edgecolors="none",
            label="finished",
            zorder=2,
        )
    else:
        ax.scatter([], [], color="#2f55ff", alpha=0.28, s=34, label="finished")

    if timeout_points:
        x_values, y_values = zip(*timeout_points, strict=True)
        ax.scatter(
            x_values,
            y_values,
            color="#ff3b30",
            marker="x",
            s=74,
            linewidths=2.0,
            label="timeout",
            clip_on=False,
            zorder=4,
        )
    else:
        ax.scatter(
            [],
            [],
            color="#ff3b30",
            marker="x",
            s=74,
            linewidths=2.0,
            label="timeout",
        )

    diagonal_max = min(parnv_timeout_seconds, narv_timeout_seconds)
    ax.plot(
        [AXIS_MIN, diagonal_max],
        [AXIS_MIN, diagonal_max],
        color="#00cc00",
        linestyle=(0, (3, 3)),
        linewidth=1.6,
        label="y=x",
        zorder=1,
    )

    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlim(AXIS_MIN, parnv_timeout_seconds)
    ax.set_ylim(AXIS_MIN, narv_timeout_seconds)
    ax.set_xlabel("PARNV (sec)", fontname="Times New Roman", fontsize=20)
    ax.set_ylabel("NARv (sec)", fontname="Times New Roman", fontsize=20)
    ax.tick_params(axis="both", which="major", labelsize=17, width=1.0)
    ax.tick_params(axis="both", which="minor", width=0.8)
    for spine in ax.spines.values():
        spine.set_linewidth(1.0)

    ax.legend(
        loc="lower right",
        frameon=True,
        fancybox=False,
        edgecolor="black",
        fontsize=15,
        handlelength=1.0,
        handletextpad=0.35,
        borderpad=0.25,
        labelspacing=0.25,
    )
    ax.grid(False)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(output_path, dpi=dpi)
    plt.close(fig)


def main() -> None:
    args = parse_args()
    parnv_rows = read_csv_rows(args.parnv_csv)
    narv_rows = read_csv_rows(args.narv_csv)
    (
        finished_points,
        timeout_points,
        skipped_pairs,
        parnv_unmatched,
        narv_unmatched,
    ) = build_paired_points(
        parnv_rows=parnv_rows,
        narv_rows=narv_rows,
        parnv_timeout_seconds=args.parnv_timeout_seconds,
        narv_timeout_seconds=args.narv_timeout_seconds,
    )

    if not finished_points and not timeout_points:
        print("warning: no plottable paired points; an empty plot will still be saved.")

    plot_points(
        finished_points=finished_points,
        timeout_points=timeout_points,
        output_path=args.output,
        parnv_timeout_seconds=args.parnv_timeout_seconds,
        narv_timeout_seconds=args.narv_timeout_seconds,
        dpi=args.dpi,
    )
    print(
        "saved plot to {} (finished={}, timeout={}, skipped_pairs={}, "
        "parnv_unmatched={}, narv_unmatched={})".format(
            args.output.resolve().as_posix(),
            len(finished_points),
            len(timeout_points),
            skipped_pairs,
            parnv_unmatched,
            narv_unmatched,
        )
    )


if __name__ == "__main__":
    main()
